version: 1
disable_existing_loggers: False

formatters:
  json_pretty:
    # Use the class from the installed library
    '()': tctk.log_formatter.ColoredJsonFormatter
    # include pathname and lineno so JSON contains file and line info
    format: "%(asctime)s %(levelname)s %(name)s %(pathname)s %(lineno)d %(message)s"
    rename_fields:
      levelname: level
      asctime: timestamp
      pathname: file_path
      lineno: line_number
    static_fields:
      service: my-app
      env: dev

handlers:
  console_handler:
    class: logging.StreamHandler
    formatter: json_pretty
    stream: ext://sys.stdout

root:
  level: INFO
  handlers: [console_handler]

loggers:
  __main__:
    level: DEBUG
    handlers: [console_handler]
    propagate: no